### PR TITLE
Mock network calls in test

### LINKED ISSUE #14: tests sometimes fail because of "header not found" error
```
RPCError {
  message: 'header not found Code: -32000',
}
```

usually rerunning the test suite fixes the problem

### PR DESCRIPTION
**Pull request by il3ven**
Closes #14 

- I have used esmock along with fetch-mock. I could have skipped fetch-mock and mocked the `transport.js` module but then the tests would have lost their purpose.
- I have tried mocking network calls *strictly*. Instead of sending a response for any call I check for the method, URL and body.
- There are still network calls for the readme tests.

A brief explanation of the syntax.

```js
const { default: getBlockNumber } = await esmock(
  "../src/blockNumber.js", // Module to be mocked
  null,
  {
   // Mock cross-fetch where ever it is imported
    "cross-fetch": {
      // This fetch-mock instance is the default export of cross-fetch
      default: fetchMock.sandbox().post(
        // Matcher object
        {
          url: options.url,
          body: {
            method: "eth_blockNumber",
          },
          matchPartialBody: true,
        },
        // Response object
        {
          result: "0xcd2057",
        }
      ),
    },
  }
);
```

### CODE REVIEW

File: test/blockNumber_test.js [hunk 1]
```diff
@@ -1,12 +1,34 @@
...
+    null,
+    {
+      "cross-fetch": {
+        default: fetchMock.sandbox().post(
+          {
+            url: options.url,
+            body: {
+              method: "eth_blockNumber",
+            },
+            matchPartialBody: true,
```
Comment (TimDaub) [inline test/blockNumber_test.js:22]: Why is `matchPartialBody` needed here? Aren't we matching the body exactly?

Comment (il3ven) [reply test/blockNumber_test.js:22]: In some cases we are not matching the whole body as the it contained a lot of parameters which added a lot of lines into the test case. I'll check once again if we can match the whole body in this case.
